### ISSUE TITLE
Revisit operators and syntax generally

### ISSUE THREAD

**Issue by mossprescott** [mossprescott/invertible-syntax#6]
The current operators are unsuccessfully aping the Haskell originals, and don't work well because the precedence is all wrong (for the most part, all the operators have the same, very low precedence). We should pick operators that read well and combine better, and also see if there's anything else that can be done with "syntax" to improve usability.

**Comment by sellout** [comment]
How about stealing the equivalent operators from Scala combinators or some other Scala combinator library, like atto[parsec]?

**Comment by mossprescott** [comment]
Mostly addressed in #10.
